# -*- coding: utf-8 -*-
"""Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVqntOHxst3xPFqpG0DkYwjeNUHTWpUk
"""

# ========================
# Vehicle Base Class
# ========================
class Vehicle:
    total_rented = 0   # class variable to track total rentals

    def __init__(self, vehicle_id, brand, model, year, rental_rate_per_day, is_available=True):
        self.vehicle_id = vehicle_id
        self.brand = brand
        self.model = model
        self.year = year
        self.rental_rate_per_day = rental_rate_per_day
        self.is_available = is_available

    def display_info(self):
        print(f"ID: {self.vehicle_id}, Brand: {self.brand}, Model: {self.model}, "
              f"Year: {self.year}, Rate/Day: {self.rental_rate_per_day}, Available: {self.is_available}")

    def rent_vehicle(self):
        if self.is_available:
            self.is_available = False
            Vehicle.total_rented += 1
            print(f"✅ Vehicle {self.vehicle_id} rented successfully.")
        else:
            print(f"❌ Vehicle {self.vehicle_id} is already rented.")

    def return_vehicle(self):
        if not self.is_available:
            self.is_available = True
            Vehicle.total_rented -= 1
            print(f"✅ Vehicle {self.vehicle_id} returned successfully.")
        else:
            print(f"⚠️ Vehicle {self.vehicle_id} was not rented.")

    @property
    def rental_cost(self):
        """Calculate estimated rental cost dynamically"""
        def cost_for_days(days):
            return self.rental_rate_per_day * days
        return cost_for_days

    @classmethod
    def get_total_rented(cls):
        return cls.total_rented


# ========================
# Car Class (Inheritance)
# ========================
class Car(Vehicle):
    def __init__(self, vehicle_id, brand, model, year, rental_rate_per_day, seats, fuel_type, is_available=True):
        super().__init__(vehicle_id, brand, model, year, rental_rate_per_day, is_available)
        self.seats = seats
        self.fuel_type = fuel_type

    def display_info(self):
        super().display_info()
        print(f"Seats: {self.seats}, Fuel: {self.fuel_type}")


# ========================
# Bike Class (Inheritance)
# ========================
class Bike(Vehicle):
    def __init__(self, vehicle_id, brand, model, year, rental_rate_per_day, cc, helmet_required, is_available=True):
        super().__init__(vehicle_id, brand, model, year, rental_rate_per_day, is_available)
        self.cc = cc
        self.helmet_required = helmet_required

    def display_info(self):
        super().display_info()
        print(f"Engine CC: {self.cc}, Helmet Required: {self.helmet_required}")


# ========================
# Customer Class
# ========================
class Customer:
    def __init__(self, customer_id, name, email):
        self.customer_id = customer_id
        self.name = name
        self.__email = email
        self.rented_vehicles = []

    # Getter for email
    def get_email(self):
        return self.__email

    # Setter for email
    def set_email(self, new_email):
        if "@" in new_email:
            self.__email = new_email
            print(f"✅ Email updated for {self.name}.")
        else:
            print("❌ Invalid email format.")

    def rent(self, vehicle):
        if vehicle.is_available:
            vehicle.rent_vehicle()
            self.rented_vehicles.append(vehicle)
            print(f"✅ {self.name} rented {vehicle.brand} {vehicle.model}.")
        else:
            print(f"❌ {vehicle.brand} {vehicle.model} is not available.")

    def return_vehicle(self, vehicle_id):
        for v in self.rented_vehicles:
            if v.vehicle_id == vehicle_id:
                v.return_vehicle()
                self.rented_vehicles.remove(v)
                print(f"✅ {self.name} returned {v.brand} {v.model}.")
                return
        print(f"⚠️ Vehicle ID {vehicle_id} not found in {self.name}'s rented list.")


# ========================
# RentalSystem Class (Composition)
# ========================
class RentalSystem:
    def __init__(self):
        self.vehicles = []
        self.customers = []

    def add_vehicle(self, vehicle):
        self.vehicles.append(vehicle)
        print(f"✅ Vehicle {vehicle.vehicle_id} added.")

    def add_customer(self, customer):
        self.customers.append(customer)
        print(f"✅ Customer {customer.name} added.")

    def search_available_vehicles(self):
        print("🚘 Available Vehicles:")
        for v in self.vehicles:
            if v.is_available:
                v.display_info()

    def show_all_rented_vehicles(self):
        print("📋 Rented Vehicles:")
        for v in self.vehicles:
            if not v.is_available:
                v.display_info()

# Create Rental System
system = RentalSystem()

# Add Vehicles
car1 = Car(101, "Toyota", "Innova", 2022, 2500, 7, "Diesel")
bike1 = Bike(201, "Yamaha", "R15", 2023, 800, 150, True)
system.add_vehicle(car1)
system.add_vehicle(bike1)

# Add Customer
cust1 = Customer(1, "Praveen", "praveen@example.com")
system.add_customer(cust1)

# Rent Vehicles
cust1.rent(car1)
cust1.rent(bike1)

# Show rented vehicles
system.show_all_rented_vehicles()

# Return a Vehicle
cust1.return_vehicle(101)

# Show available vehicles
system.search_available_vehicles()

# Show total rented vehicles using class method
print("🔢 Total vehicles rented so far:", Vehicle.get_total_rented())

# Rental cost calculation using @property
days = 3
print(f"💰 Estimated cost for {days} days (Car): {car1.rental_cost(days)}")

